name: alpine

on:
  push:
    branches:
      - main
    paths:
      - alpine/**
      - .github/workflows/alpine.yaml
  schedule:
    - cron:  '10 0 * * 0'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./alpine
        file: ./alpine/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine:latest

    - name: Scan for vulnerabilities
      id: scan
      uses: crazy-max/ghaction-container-scan@v3
      with:
        image: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine:latest
        dockerfile: ./alpine/Dockerfile

    - name: Upload SARIF file
      if: ${{ steps.scan.outputs.sarif != '' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
